---
title: "LOL Updated Data"
author: "Jannine Chamorro"
date: "4/7/2020"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(png)

#Mid
#LL49.2013<-read.csv(file="BMRMUSCALL49_20130.csv")
#LL49.2014<-read.csv(file="BMRMUSCALL49_20140.csv")
LL49.2015<-read.csv(file="BMRMUSCALL49_20150.csv")
LL49.2016<-read.csv(file="BMRMUSCALL49_20160.csv")
LL49.2018<-read.csv(file="BMRMUSCALL49_20180.csv")

#Low
LL51.2015<-read.csv(file="BMRMUSCALL51_20150.csv")

#Mid
#LL52.2013<-read.csv(file="BMRMUSCALL52_20130.csv")
#LL52.2014<-read.csv(file="BMRMUSCALL52_20140.csv")
LL52.2015<-read.csv(file="BMRMUSCALL52_20150.csv")
LL52.2016<-read.csv(file="BMRMUSCALL52_20160.csv")

#High
#LL54.2013<-read.csv(file="BMRMUSCALL54_20130.csv")
#LL54.2014<-read.csv(file="BMRMUSCALL54_20140.csv")
LL54.2015<-read.csv(file="BMRMUSCALL54_20150.csv")
LL54.2016<-read.csv(file="BMRMUSCALL54_20160.csv")

#Low
#LL63.2013<-read.csv(file="BMRMUSCALL63_20130.csv")
#LL63.2014<-read.csv(file="BMRMUSCALL63_20140.csv")

#Low
LL64.2016<-read.csv(file="BMRMUSCALL64_20160.csv")

#Low-Mid
#LL50.2018<-read.csv(file="BMRMUSCALL50_20180.csv")
```

```{r}
#Adding Logger id
#LL63.2013$logger<-"BMRMUSCALL63"
#LL63.2014$logger<-"BMRMUSCALL63"

LL51.2015$logger<-"BMRMUSCALL51"

LL64.2016$logger<-"BMRMUSCALL64"

#LL49.2013$logger<-"BMRMUSCALL49"
#LL49.2014$logger<-"BMRMUSCALL49"
LL49.2015$logger<-"BMRMUSCALL49"
LL49.2016$logger<-"BMRMUSCALL49"
LL49.2018$logger<-"BMRMUSCALL49"

#Adding Site (LOL)
#LL63.2013$site<-"LOL"
#LL63.2014$site<-"LOL"

LL51.2015$site<-"LOL"

LL64.2016$site<-"LOL"

#LL49.2013$site<-"LOL"
#LL49.2014$site<-"LOL"
LL49.2015$site<-"LOL"
LL49.2016$site<-"LOL"
LL49.2018$site<-"LOL"

#Adding zone (Low)
#LL63.2013$zone<-"low"
#LL63.2014$zone<-"low"

LL51.2015$zone<-"low"

LL64.2016$zone<-"low"

#LL49.2013$zone<-"low"
#LL49.2014$zone<-"low"
LL49.2015$zone<-"low"
LL49.2016$zone<-"low"
LL49.2018$zone<-"low"


#Adding Logger id
#LL49.2013$logger<-"BMRMUSCALL49"
#LL49.2014$logger<-"BMRMUSCALL49"
LL49.2015$logger<-"BMRMUSCALL49"
LL49.2016$logger<-"BMRMUSCALL49"
LL49.2018$logger<-"BMRMUSCALL49"

##LL52.2013$logger<-"BMRMUSCALL52"
##LL52.2014$logger<-"BMRMUSCALL52"
LL52.2015$logger<-"BMRMUSCALL52"
LL52.2016$logger<-"BMRMUSCALL52"

#Adding site (LOL)
##LL49.2013$site<-"LOL"
##LL49.2014$site<-"LOL"
LL49.2015$site<-"LOL"
LL49.2016$site<-"LOL"
LL49.2018$site<-"LOL"

#LL52.2013$site<-"LOL"
#LL52.2014$site<-"LOL"
LL52.2015$site<-"LOL"
LL52.2016$site<-"LOL"

#Adding Zone (Mid)
#LL49.2013$zone<-"mid"
#LL49.2014$zone<-"mid"
LL49.2015$zone<-"mid"
LL49.2016$zone<-"mid"
LL49.2018$zone<-"mid"

#LL52.2013$zone<-"mid"
#LL52.2014$zone<-"mid"
LL52.2015$zone<-"mid"
LL52.2016$zone<-"mid"

#Adddinng Logger id
#LL54.2013$logger<-"BMRMUSCALL54"
#LL54.2014$logger<-"BMRMUSCALL54"
LL54.2015$logger<-"BMRMUSCALL54"
LL54.2016$logger<-"BMRMUSCALL54"

#Adding Site (LOL)
#LL54.2013$site<-"LOL"
#LL54.2014$site<-"LOL"
LL54.2015$site<-"LOL"
LL54.2016$site<-"LOL"

#Adding Zone (High)
#LL54.2013$zone<-"high"
#LL54.2014$zone<-"high"
LL54.2015$zone<-"high"
LL54.2016$zone<-"high"

#Adding logger id, site and zone (LowMid)
#LL50.2018$logger<-"BMRMUSCALL50"
#LL50.2018$site<-"LOL"
#LL50.2018$zone<-"lower-mid"


#lol_robo_updated<-rbind(LL49.2013, LL49.2014)
lol_robo_updated<-rbind( LL49.2015, LL49.2016)
lol_robo_updated<-rbind(lol_robo_updated, LL49.2016)
lol_robo_updated<-rbind(lol_robo_updated, LL49.2018)
lol_robo_updated<-rbind(lol_robo_updated, LL51.2015)
#lol_robo_updated<-rbind(lol_robo_updated, LL52.2013)
#lol_robo_updated<-rbind(lol_robo_updated, LL52.2014)
lol_robo_updated<-rbind(lol_robo_updated, LL52.2015)
lol_robo_updated<-rbind(lol_robo_updated, LL52.2016)
#lol_robo_updated<-rbind(lol_robo_updated, LL54.2013)
#lol_robo_updated<-rbind(lol_robo_updated, LL54.2014)
lol_robo_updated<-rbind(lol_robo_updated, LL54.2015)
lol_robo_updated<-rbind(lol_robo_updated, LL54.2016)
#lol_robo_updated<-rbind(lol_robo_updated, LL63.2013)
lol_robo_updated<-rbind(lol_robo_updated, LL64.2016)
#lol_robo_updated<-rbind(lol_robo_updated, LL50.2018)


write.csv(lol_robo_updated, 'lol_robo_updated.csv')
```

